<?php
// 一次性：把 /var/lib/it-ccra/*.sqlite 搬到 PostgreSQL（itccra），每個檔一個 schema、表名欄位照舊。
// 熊哥 2026-10-06：「現在就改吧」「我最初定位不是就要使用php+pqsql」。
// 用法：sudo -u www-data php migrate_sqlite_to_pg.php [--apply]
//   不帶 --apply 只印出計畫與筆數；帶 --apply 才重建 schema 並搬資料（會先 DROP 該 schema，可重跑）。
// 搬完逐表核對筆數，不一致就整個停下來（失敗方向是不切換）。
require '/var/www/it-lib/db.php';
$apply = in_array('--apply', $argv, true);
$ok = true;
foreach (glob('/var/lib/it-ccra/*.sqlite') as $f) {
    $schema = basename($f, '.sqlite');
    $s = new PDO('sqlite:' . $f);
    $s->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $tables = $s->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'")->fetchAll(PDO::FETCH_COLUMN);
    $pg = itdb($schema);
    if ($apply) { $pg->exec("DROP SCHEMA IF EXISTS $schema CASCADE"); $pg->exec("CREATE SCHEMA $schema"); $pg->exec("SET search_path TO $schema"); }
    foreach ($tables as $t) {
        $cols = $s->query("PRAGMA table_info($t)")->fetchAll(PDO::FETCH_ASSOC);
        $pkCols = array_values(array_filter($cols, fn($c) => $c['pk'] > 0));
        $defs = [];
        $identity = null;
        foreach ($cols as $c) {
            $type = strtoupper($c['type'] ?: 'TEXT');
            $type = str_contains($type, 'INT') ? 'BIGINT' : (str_contains($type, 'REAL') ? 'DOUBLE PRECISION' : 'TEXT');
            $def = '"' . $c['name'] . '" ' . $type;
            if (count($pkCols) === 1 && $c['pk'] > 0 && $type === 'BIGINT') { $def .= ' GENERATED BY DEFAULT AS IDENTITY'; $identity = $c['name']; }
            if ($c['dflt_value'] !== null) $def .= ' DEFAULT ' . str_replace('"', "'", $c['dflt_value']);
            $defs[] = $def;
        }
        if ($pkCols) $defs[] = 'PRIMARY KEY (' . implode(',', array_map(fn($c) => '"' . $c['name'] . '"', $pkCols)) . ')';
        $ddl = "CREATE TABLE $t (" . implode(', ', $defs) . ')';
        $rows = $s->query("SELECT * FROM $t")->fetchAll(PDO::FETCH_ASSOC);
        echo "$schema.$t  " . count($rows) . " 筆  " . ($apply ? '' : $ddl) . PHP_EOL;
        if (!$apply) continue;
        $pg->exec($ddl);
        $names = array_map(fn($c) => $c['name'], $cols);
        $ins = $pg->prepare("INSERT INTO $t (" . implode(',', array_map(fn($n) => '"' . $n . '"', $names)) . ') OVERRIDING SYSTEM VALUE VALUES (' . implode(',', array_fill(0, count($names), '?')) . ')');
        foreach ($rows as $r) $ins->execute(array_map(fn($n) => $r[$n], $names));
        if ($identity) $pg->exec("SELECT setval(pg_get_serial_sequence('$schema.$t', '$identity'), GREATEST((SELECT COALESCE(MAX(\"$identity\"), 0) FROM $t), 1), (SELECT COUNT(*) > 0 FROM $t))");
        $n = (int)$pg->query("SELECT COUNT(*) FROM $t")->fetchColumn();
        if ($n !== count($rows)) { echo "  🔴 筆數不符 PG=$n SQLite=" . count($rows) . PHP_EOL; $ok = false; }
    }
}
echo $ok ? "OK\n" : "FAIL\n";
exit($ok ? 0 : 1);
