<?php
// it.ccra.tw 資料庫連線（PostgreSQL）。
// 熊哥 2026-10-06：「我最初定位不是就要使用php+pqsql」——原本各服務各用一個 SQLite 檔，當日改為 PostgreSQL。
// 資料庫 itccra（ITSrv01 本機，獨立帳號，不與 Zabbix 共用）；連線資訊在 /var/lib/it-ccra/pg.json（www-data 640，不進 GitHub）。
// 每個舊的 SQLite 檔對應一個 schema，名稱照舊（ai_apply／repair／shortlink…），itdb('repair') 會把 search_path 設到該 schema，
// 所以原本的 SQL（表名 users、apply、act…）不必改名。
// ⚠️ 與 SQLite 的差異：字串常值一律用單引號（雙引號在 PG 是識別字）；INSERT OR IGNORE 改 ON CONFLICT DO NOTHING；
//    自動編號欄位是 GENERATED BY DEFAULT AS IDENTITY（不是 INTEGER PRIMARY KEY 就會自動遞增）。
const PG_CONF = '/var/lib/it-ccra/pg.json';

function itdb(string $schema): PDO {
    static $conns = [];
    if (!preg_match('/^[a-z_]+$/', $schema)) throw new InvalidArgumentException('bad schema');
    if (isset($conns[$schema])) return $conns[$schema];
    $c = json_decode((string)file_get_contents(PG_CONF), true);
    $d = new PDO("pgsql:host={$c['host']};dbname={$c['db']}", $c['user'], $c['pass'],
                 [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    $d->exec("CREATE SCHEMA IF NOT EXISTS $schema");
    $d->exec("SET search_path TO $schema");
    return $conns[$schema] = $d;
}

// 取代 SQLite 的 PRAGMA table_info：回傳欄位名稱陣列
function itdb_cols(PDO $d, string $table): array {
    $s = $d->prepare('SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ?');
    $s->execute([$table]);
    return $s->fetchAll(PDO::FETCH_COLUMN);
}
